apiVersion: "v1"
kind: Pod
metadata:
  name: broker
  labels:
    app: broker
spec:
  containers:
    - name: broker
      image: jberkhahn/more_service_broker
      ports:
        - containerPort: 4567
          protocol: TCP
